
import 'package:shoesly/model/shoes_model/shoes_model.dart';
import 'package:shoesly/utils/app_image.dart';

final List<Shoes> ShoesData = [
  Shoes(
      brand: 'Nike',
      model: 'Air Max 270',
      price: 150.0,
      color: 'Red',
      size: '10',
      ratings: 4.2,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. ', 'Good cushioning'],
      imageUrl: AppImage().nike),
  Shoes(
      brand: 'Nike',
      model: 'Air Force 1',
      price: 120.0,
      color: 'White',
      size: '9',
      ratings: 3.7,
      review: ['Classic design', 'Durable', 'Versatile'],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Adidas',
      model: 'Ultraboost 21',
      price: 180.0,
      color: 'Black',
      size: '9',
      ratings: 3.5,
      review: ['Extremely Perfect for keeping your feet dry and warm in damp conditions. ', 'Great support', 'Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Adidas',
      model: 'NMD_R1',
      price: 140.0,
      color: 'Blue',
      size: '10',
      ratings: 3.5,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Lightweight', 'Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Puma',
      model: 'RS-X',
      price: 110.0,
      color: 'Green',
      size: '8',
      ratings: 3.5,
      review: ['Unique design', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Good value'],
      imageUrl: AppImage().shoes),
  Shoes(
      brand: 'Puma',
      model: 'Suede Classic',
      price: 70.0,
      color: 'Black',
      size: '9',
      ratings: 3.5,
      review: ['Classic look Perfect for keeping your feet dry and warm in damp conditions.  Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Reebok',
      model: 'Club C 85',
      price: 75.0,
      color: 'White',
      size: '10',
      ratings: 3.1,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Retro style', 'Good quality'],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Reebok',
      model: 'Nano X1',
      price: 130.0,
      color: 'Grey',
      size: '11',
      ratings: 4.3,
      review: ['Great for training', 'Supportive', 'Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'New Balance',
      model: '990v5',
      price: 175.0,
      color: 'Grey',
      size: '10',
      ratings: 3.9,
      review: ['Classic Stylish look for Excellent quality Perfect for keeping your feet dry and warm in damp conditions. ', 'Very Perfect for keeping your feet dry and warm in damp conditions. ', 'Supportive'],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'New Balance',
      model: '574',
      price: 80.0,
      color: 'Navy',
      size: '9',
      ratings: 4.2,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Classic style', 'Good value'],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Nike',
      model: 'Blazer Mid',
      price: 100.0,
      color: 'Black',
      size: '11',
      ratings: 4.6,
      review: ['Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Durable'],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Nike',
      model: 'React Element 55',
      price: 130.0,
      color: 'White',
      size: '10',
      ratings: 4.7,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Modern design', 'Great for running'],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Adidas',
      model: 'Superstar',
      price: 85.0,
      color: 'White',
      size: '8',
      ratings: 4.0,
      review: ['Classic look Perfect for keeping your feet dry and warm in damp conditions.  Perfect for keeping your feet dry and warm in damp conditions. ', 'Durable', 'Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Adidas',
      model: 'Stan Smith',
      price: 90.0,
      color: 'Green',
      size: '9',
      ratings: 4.3,
      review: ['Timeless design', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Versatile'],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Puma',
      model: 'Cali',
      price: 75.0,
      color: 'Pink',
      size: '7',
      ratings: 4.1,
      review: ['Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Good value'],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Puma',
      model: 'Future Rider',
      price: 80.0,
      color: 'Blue',
      size: '8',
      ratings: 4.0,
      review: ['Retro design', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Reebok',
      model: 'Zig Kinetica',
      price: 120.0,
      color: 'Orange',
      size: '10',
      ratings: 4.4,
      review: ['Unique design', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Good for running'],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Reebok',
      model: 'Classic Leather',
      price: 75.0,
      color: 'Black',
      size: '9',
      ratings: 4.2,
      review: ['Classic look Perfect for keeping your feet dry and warm in damp conditions.  Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Durable'],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'New Balance',
      model: 'Fresh Foam 1080v11',
      price: 150.0,
      color: 'Blue',
      size: '10',
      ratings: 4.8,
      review: ['Very Perfect for keeping your feet dry and warm in damp conditions. ', 'Great support', 'Excellent for running'],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'New Balance',
      model: 'FuelCell Rebel v2',
      price: 130.0,
      color: 'Yellow',
      size: '11',
      ratings: 4.7,
      review: ['Lightweight', 'Great for running', 'Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Nike',
      model: 'ZoomX Vaporfly',
      price: 250.0,
      color: 'Orange',
      size: '10',
      ratings: 3.9,
      review: ['High performance', 'Very Perfect for keeping your feet dry and warm in damp conditions. ', 'Excellent for marathons'],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Nike',
      model: 'Pegasus Trail 2',
      price: 130.0,
      color: 'Green',
      size: '9',
      ratings: 4.0,
      review: ['Great for trails', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Durable'],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Adidas',
      model: 'Terrex Swift R2',
      price: 120.0,
      color: 'Black',
      size: '10',
      ratings: 4.4,
      review: ['Great for hiking', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Durable'],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Adidas',
      model: 'Solar Glide 3',
      price: 140.0,
      color: 'White',
      size: '8',
      ratings: 4.3,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Great for running', 'Supportive'],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Puma',
      model: 'Enzo 2',
      price: 65.0,
      color: 'Black',
      size: '9',
      ratings: 4.1,
      review: ['Good value', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Puma',
      model: 'X-Ray',
      price: 75.0,
      color: 'Red',
      size: '10',
      ratings: 4.2,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Good value', 'Classic Stylish look Perfect for keeping your feet dry and warm in damp conditions. '],
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Reebok',
      model: 'Floatride Run',
      price: 150.0,
      color: 'Blue',
      size: '11',
      ratings: 4.7,
      review: ['Great for running', 'Very Perfect for keeping your feet dry and warm in damp conditions. ', 'Supportive'],
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Reebok',
      model: 'Astroride Strike 2',
      price: 70.0,
      color: 'Grey',
      size: '8',
      ratings: 3.5,
      review: ['Perfect for keeping your feet dry and warm in damp conditions. ', 'Perfect for keeping your feet dry and warm in damp conditions. ', 'Good for walking'],
      imageUrl: AppImage().puma),
];