import 'package:shoesly/utils/app_image.dart';
import 'shoes_model.dart';

final List<Shoes> ShoesData = [
  Shoes(
      brand: 'Nike',
      model: 'Air Max 270',
      price: 150.0,
      color: 'Red',
      size: '10',
      imageUrl: AppImage().nike),
  Shoes(
      brand: 'Nike',
      model: 'Air Force 1',
      price: 120.0,
      color: 'White',
      size: '9',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Adidas',
      model: 'Ultraboost 21',
      price: 180.0,
      color: 'Black',
      size: '9',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Adidas',
      model: 'NMD_R1',
      price: 140.0,
      color: 'Blue',
      size: '10',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Puma',
      model: 'RS-X',
      price: 110.0,
      color: 'Green',
      size: '8',
      imageUrl: AppImage().shoes),
  Shoes(
      brand: 'Puma',
      model: 'Suede Classic',
      price: 70.0,
      color: 'Black',
      size: '9',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Reebok',
      model: 'Club C 85',
      price: 75.0,
      color: 'White',
      size: '10',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Reebok',
      model: 'Nano X1',
      price: 130.0,
      color: 'Grey',
      size: '11',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'New Balance',
      model: '990v5',
      price: 175.0,
      color: 'Grey',
      size: '10',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'New Balance',
      model: '574',
      price: 80.0,
      color: 'Navy',
      size: '9',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Nike',
      model: 'Blazer Mid',
      price: 100.0,
      color: 'Black',
      size: '11',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Nike',
      model: 'React Element 55',
      price: 130.0,
      color: 'White',
      size: '10',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Adidas',
      model: 'Superstar',
      price: 85.0,
      color: 'White',
      size: '8',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Adidas',
      model: 'Stan Smith',
      price: 90.0,
      color: 'Green',
      size: '9',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Puma',
      model: 'Cali',
      price: 75.0,
      color: 'Pink',
      size: '7',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Puma',
      model: 'Future Rider',
      price: 80.0,
      color: 'Blue',
      size: '8',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Reebok',
      model: 'Zig Kinetica',
      price: 120.0,
      color: 'Orange',
      size: '10',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Reebok',
      model: 'Classic Leather',
      price: 75.0,
      color: 'Black',
      size: '9',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'New Balance',
      model: 'Fresh Foam 1080v11',
      price: 150.0,
      color: 'Blue',
      size: '10',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'New Balance',
      model: 'FuelCell Rebel v2',
      price: 130.0,
      color: 'Yellow',
      size: '11',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Nike',
      model: 'ZoomX Vaporfly',
      price: 250.0,
      color: 'Orange',
      size: '10',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Nike',
      model: 'Pegasus Trail 2',
      price: 130.0,
      color: 'Green',
      size: '9',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Adidas',
      model: 'Terrex Swift R2',
      price: 120.0,
      color: 'Black',
      size: '10',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Adidas',
      model: 'Solar Glide 3',
      price: 140.0,
      color: 'White',
      size: '8',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Puma',
      model: 'Enzo 2',
      price: 65.0,
      color: 'Black',
      size: '9',
      imageUrl: AppImage().adidas),
  Shoes(
      brand: 'Puma',
      model: 'X-Ray',
      price: 75.0,
      color: 'Red',
      size: '10',
      imageUrl: AppImage().puma),
  Shoes(
      brand: 'Reebok',
      model: 'Floatride Run',
      price: 150.0,
      color: 'Blue',
      size: '11',
      imageUrl: AppImage().newBalance),
  Shoes(
      brand: 'Reebok',
      model: 'Astroride Strike 2',
      price: 70.0,
      color: 'Grey',
      size: '8',
      imageUrl: AppImage().puma
  ),
];